import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import './lib/api';
// import '../../styles/dashboard.css' // Import the v4 CSS

// import Navbar from "./components/navbar/navbar";
import Footer from "./components/footer/footer";
// import { personalInfo } from "./data/personalInfo"; // import shared data
import personalInfoData from '@/data/personalInfo';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Pass only data, no functions */}
        {/* <Navbar personalInfoData={personalInfoData} /> */}
        {children}
        {/* <Footer personalInfoData={personalInfoData} /> */}
      </body>
    </html>
  );
}
